wip

diff --git a/.github/workflows/2-release-verify-build-deploy.yml b/.github/workflows/2-release-verify-build-deploy.yml
--- a/.github/workflows/2-release-verify-build-deploy.yml
+++ b/.github/workflows/2-release-verify-build-deploy.yml
@@ -54,7 +54,7 @@ jobs:
         run: |
           TAG_LIST=(`echo $RELEASE_VERSION | tr '.' ' '`)
           # Exit if invalid semver
-          [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "Invalid Semantic versioning string" && return 1
+          [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "Invalid Semantic versioning string" && exit 1
 
       - run: echo "::set-env name=RELEASE_NAME::rc-${RELEASE_VERSION}-${{ github.event.pull_request.head.sha }}" # new run because can not use $RELEASE_VERSION in same run
       - name: "echo ENV_VARIABLE"
@@ -120,6 +120,12 @@ jobs:
           echo "::set-env name=RELEASE_VERSION::${GITHUB_HEAD_REF##*release-}"
           echo "::set-env name=IMAGE_REGISTRY::docker.io/${DOCKER_USERNAME}/$DOCKER_IMAGE"
 
+      - name: "Verify Semantic versioning pattern"
+        run: |
+          TAG_LIST=(`echo $RELEASE_VERSION | tr '.' ' '`)
+          # Exit if invalid semver
+          [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "Invalid Semantic versioning string" && exit 1
+          
       - run: echo "::set-env name=RELEASE_NAME::${RELEASE_VERSION}" # new run because can not use $RELEASE_VERSION in same run
       - name: "echo ENV_VARIABLE"
         run: |
