wip

diff --git a/.github/workflows/3-hotfix-verify-build-deploy.yml.yml b/.github/workflows/3-hotfix-verify-build-deploy.yml.yml
--- a/.github/workflows/3-hotfix-verify-build-deploy.yml.yml
+++ b/.github/workflows/3-hotfix-verify-build-deploy.yml.yml
@@ -61,7 +61,9 @@ jobs:
           echo "::set-env name=RELEASE_VERSION::${V_MAJOR}.${V_MINOR}.${V_PATCH}"
           echo "::set-env name=IMAGE_REGISTRY::docker.io/${DOCKER_USERNAME}/$DOCKER_IMAGE"
 
-      - run: echo "::set-env name=RELEASE_NAME::rc-${RELEASE_VERSION}-${{ github.event.pull_request.head.sha }}" # new run because can not use $RELEASE_VERSION in same run
+      - name: "Sets RELEASE_NAME"
+        run: echo "::set-env name=RELEASE_NAME::rc-${RELEASE_VERSION}-${{ github.event.pull_request.head.sha }}" # new run because can not use $RELEASE_VERSION in same run
+      
       - name: "echo ENV_VARIABLE"
         run: |
           echo BRANCH_NAME: "$GITHUB_HEAD_REF"
@@ -71,28 +73,28 @@ jobs:
           echo IMAGE_REGISTRY: $IMAGE_REGISTRY
           echo DOCKER_USERNAME: $DOCKER_USERNAME
 
-      # ## Sets Maven version ##
-      # - name: Sets Maven Release Candidate version in pom.xml
-      #   run: mvn versions:set -DnewVersion=$RELEASE_NAME
-      # ## Push to image registry ##
-      # - name: Build & Push Release Candidate to Docker registry
-      #   run: |
-      #     mvn clean compile -P staging-k8s jib:build \
-      #       -Djib.to.auth.username=$DOCKER_USERNAME \
-      #       -Djib.to.auth.password=$DOCKER_PASSWORD \
-      #       -Djib.to.image=$IMAGE_REGISTRY \
-      #       -Djib.to.tags=$RELEASE_NAME
-      # ## Commit maven version update ##
-      # ## If protected can use force push with admin right and skip-ci
-      # - name: "Committing changes to branch \"${{ github.head_ref }}\""
-      #   run: |
-      #     git config --global user.name $GITHUB_USERNAME
-      #     git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
-      #     git diff
-      #     git add .
-      #     git commit \
-      #       -m "version updated to '$RELEASE_NAME' in pom.xml & image pushed to registry 'docker.io/${DOCKER_USERNAME}/${DOCKER_IMAGE}:$RELEASE_NAME'"
-      #     git push origin $GITHUB_HEAD_REF
+      ## Sets Maven version ##
+      - name: Sets Maven Release Candidate version in pom.xml
+        run: mvn versions:set -DnewVersion=$RELEASE_NAME
+      ## Push to image registry ##
+      - name: Build & Push Release Candidate to Docker registry
+        run: |
+          mvn clean compile -P staging-k8s jib:build \
+            -Djib.to.auth.username=$DOCKER_USERNAME \
+            -Djib.to.auth.password=$DOCKER_PASSWORD \
+            -Djib.to.image=$IMAGE_REGISTRY \
+            -Djib.to.tags=$RELEASE_NAME
+      ## Commit maven version update ##
+      ## If protected can use force push with admin right and skip-ci
+      - name: "Committing changes to branch \"${{ github.head_ref }}\""
+        run: |
+          git config --global user.name $GITHUB_USERNAME
+          git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
+          git diff
+          git add .
+          git commit \
+            -m "version updated to '$RELEASE_NAME' in pom.xml & image pushed to registry 'docker.io/${DOCKER_USERNAME}/${DOCKER_IMAGE}:$RELEASE_NAME'"
+          git push origin $GITHUB_HEAD_REF
 
   # Does not deloy to k8s master => GitOps pattern (flux will do it automatically)
   hotfix-build-and-deploy-master:
@@ -119,10 +121,23 @@ jobs:
       ## Sets environment variables ##
       - name: "Sets ENV_VARIABLE"
         run: |
-          echo "::set-env name=RELEASE_VERSION::${GITHUB_HEAD_REF##*release-}"
+          echo ">>> Pulling last tags"
+          git fetch --prune --tags
+          # Gets and bumps tag version
+          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
+          TAG_LIST=(`echo $LATEST_TAG | tr '.' ' '`)
+          # Exit if tag has invalid pattern
+          [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "Invalid Semantic versioning string" && return 1
+          #
+          V_MAJOR=${TAG_LIST[0]}
+          V_MINOR=${TAG_LIST[1]}
+          V_PATCH=$(( ${TAG_LIST[2]} + 1))
+          echo "::set-env name=RELEASE_VERSION::${V_MAJOR}.${V_MINOR}.${V_PATCH}"
           echo "::set-env name=IMAGE_REGISTRY::docker.io/${DOCKER_USERNAME}/$DOCKER_IMAGE"
 
-      - run: echo "::set-env name=RELEASE_NAME::${RELEASE_VERSION}" # new run because can not use $RELEASE_VERSION in same run
+      - name: "Sets RELEASE_NAME"
+        run: echo "::set-env name=RELEASE_NAME::${RELEASE_VERSION}" # new run because can not use $RELEASE_VERSION in same run
+      
       - name: "echo ENV_VARIABLE"
         run: |
           echo BRANCH_NAME: "$GITHUB_HEAD_REF"
@@ -153,7 +168,7 @@ jobs:
         run: |
           git config --global user.name $GITHUB_USERNAME
           git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
-          # synchronizes with the remote repositories (in order to be able to checkout to master)
+          # Sync with remote repo to checkout master
           git fetch
           git checkout master
           git diff
@@ -162,5 +177,5 @@ jobs:
 
       - name: Create & push tag
         run: |
-          git tag -a $RELEASE_VERSION -m "Release: $RELEASE_VERSION"
+          git tag -a $RELEASE_VERSION -m "Hotfix release: $RELEASE_VERSION"
           git push origin $RELEASE_VERSION
